[[plugins]]
repo = 'Shougo/dein.vim'

#Set the buffer filetype based on the code block the cursor currently resides in.
#The code block filetype is determined by the context_filetype.vim plugin.
[[plugins]] 
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]] # jsx highlight
repo = 'mxw/vim-jsx'
[[plugins]] #javascript highlight
repo = 'pangloss/vim-javascript'

[[plugins]] # colorscheme
repo = 'joshdick/onedark.vim'
hook_add = '''
  "set background=dark
  "Use VimEnter on the grounds that you have to setting colorscheme after source command.
  " and grant nented option because of avoidance of restrain event call.
  au MyAutoCmd VimEnter * nested colorscheme onedark
'''

[[plugins]] # deoplete
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]] # NERDTree
repo = 'scrooloose/nerdtree'
